"""
PolarMesh TinyML Autoencoder Model Trainer & C Header Exporter
Trains a lightweight 1D reconstruction autoencoder for edge anomaly detection on STM32L4.
"""

import json
import numpy as np
import os

def load_data(filepath="ml/southern_ocean_ctd_dataset.json"):
    with open(filepath, "r") as f:
        data = json.load(f)
    
    X_normal = []
    X_anomaly = []
    
    for item in data:
        # Feature vector: 16 depths x 3 channels (temp, salinity, density) = 48 features
        feature_vector = []
        for t, s, d in zip(item["temperatures_c"], item["salinities_psu"], item["densities_kg_m3"]):
            feature_vector.extend([t, s, d])
            
        if item["anomaly"] == "NONE":
            X_normal.append(feature_vector)
        else:
            X_anomaly.append((feature_vector, item["anomaly"]))
            
    return np.array(X_normal, dtype=np.float32), X_anomaly

def train_linear_autoencoder(X_train, latent_dim=8, epochs=100, lr=0.01):
    """
    Compact bottleneck autoencoder (48 -> 8 -> 48).
    Ideal for Cortex-M4 DSP with minimal RAM footprint (<1.5 KB).
    """
    n_samples, n_features = X_train.shape
    
    # Simple PCA-based optimal projection initialization
    X_mean = np.mean(X_train, axis=0)
    X_centered = X_train - X_mean
    
    cov = np.cov(X_centered, rowvar=False)
    eigenvalues, eigenvectors = np.linalg.eigh(cov)
    
    # Top latent_dim eigenvectors form encoder weights
    idx = np.argsort(eigenvalues)[::-1]
    W_enc = eigenvectors[:, idx[:latent_dim]] # Shape (48, 8)
    W_dec = W_enc.T                           # Shape (8, 48)
    
    return X_mean, W_enc, W_dec

def export_c_header(X_mean, W_enc, W_dec, threshold, output_path="firmware/include/anomaly_model_weights.h"):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    latent_dim = W_enc.shape[1]
    n_features = W_enc.shape[0]
    
    with open(output_path, "w") as f:
        f.write("/**\n * @file anomaly_model_weights.h\n * @brief Pre-trained TinyML Autoencoder Model Weights\n * Auto-generated by ml/train_anomaly_detector.py\n */\n\n")
        f.write("#ifndef ANOMALY_MODEL_WEIGHTS_H\n#define ANOMALY_MODEL_WEIGHTS_H\n\n")
        f.write(f"#define MODEL_INPUT_DIM     {n_features}\n")
        f.write(f"#define MODEL_LATENT_DIM    {latent_dim}\n")
        f.write(f"#define MODEL_MSE_THRESHOLD {threshold:.6f}f\n\n")
        
        # Mean vector
        f.write("static const float model_mean[MODEL_INPUT_DIM] = {\n  ")
        f.write(", ".join([f"{v:.5f}f" for v in X_mean]))
        f.write("\n};\n\n")
        
        # Encoder weights
        f.write("static const float model_encoder_w[MODEL_INPUT_DIM][MODEL_LATENT_DIM] = {\n")
        for row in W_enc:
            f.write("  { " + ", ".join([f"{v:.5f}f" for v in row]) + " },\n")
        f.write("};\n\n")
        
        f.write("#endif /* ANOMALY_MODEL_WEIGHTS_H */\n")
        
    print(f"Exported TinyML model weights -> {output_path}")

if __name__ == "__main__":
    X_normal, anomalies = load_data()
    print(f"Training dataset: {len(X_normal)} normal profiles, {len(anomalies)} anomalies")
    
    X_mean, W_enc, W_dec = train_linear_autoencoder(X_normal, latent_dim=8)
    
    # Calculate baseline reconstruction error on normal data
    recon_errors_normal = []
    for x in X_normal:
        centered = x - X_mean
        z = np.dot(centered, W_enc)
        x_rec = np.dot(z, W_dec) + X_mean
        mse = np.mean((x - x_rec) ** 2)
        recon_errors_normal.append(mse)
        
    threshold = float(np.percentile(recon_errors_normal, 99.0) * 1.5)
    print(f"Normal Mean MSE: {np.mean(recon_errors_normal):.5f}, 99th Percentile: {np.percentile(recon_errors_normal, 99):.5f}")
    print(f"Established Anomaly Threshold: {threshold:.5f}")
    
    # Test on anomalies
    flagged = 0
    for x, anom_type in anomalies:
        centered = x - X_mean
        z = np.dot(centered, W_enc)
        x_rec = np.dot(z, W_dec) + X_mean
        mse = np.mean((x - x_rec) ** 2)
        if mse > threshold:
            flagged += 1
            
    print(f"Anomaly Detection Recall: {flagged}/{len(anomalies)} ({flagged/len(anomalies)*100:.1f}%)")
    export_c_header(X_mean, W_enc, W_dec, threshold)
